2024-03-16 13:28:25,303 ERROR: Exception on /explore [GET] [in /Users/gavino/ifa/tutorial/myenv/lib/python3.10/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/Users/gavino/ifa/tutorial/myenv/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/gavino/ifa/tutorial/myenv/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/gavino/ifa/tutorial/myenv/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/gavino/ifa/tutorial/myenv/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/gavino/ifa/tutorial/myenv/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/gavino/ifa/tutorial/app/routes.py", line 135, in explore
    return render_template('explore.html', title='Explore', snacks=snacks.items, next_url=next_url, prev_url=prev_url, search_query=search_query)
NameError: name 'next_url' is not defined
2024-03-16 13:28:26,567 ERROR: Exception on /explore [GET] [in /Users/gavino/ifa/tutorial/myenv/lib/python3.10/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/Users/gavino/ifa/tutorial/myenv/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/gavino/ifa/tutorial/myenv/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/gavino/ifa/tutorial/myenv/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/gavino/ifa/tutorial/myenv/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/gavino/ifa/tutorial/myenv/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/gavino/ifa/tutorial/app/routes.py", line 135, in explore
    return render_template('explore.html', title='Explore', snacks=snacks.items, next_url=next_url, prev_url=prev_url, search_query=search_query)
NameError: name 'next_url' is not defined
2024-03-16 13:28:52,066 ERROR: Exception on /explore [GET] [in /Users/gavino/ifa/tutorial/myenv/lib/python3.10/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/Users/gavino/ifa/tutorial/myenv/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/gavino/ifa/tutorial/myenv/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/gavino/ifa/tutorial/myenv/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/gavino/ifa/tutorial/myenv/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/gavino/ifa/tutorial/myenv/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/gavino/ifa/tutorial/app/routes.py", line 135, in explore
    return render_template('explore.html', title='Explore', snacks=snacks.items, next_url=next_url, prev_url=prev_url, search_query=search_query)
NameError: name 'next_url' is not defined
2024-03-16 13:31:38,939 INFO: Microblog startup [in /Users/gavino/ifa/tutorial/app/__init__.py:31]
2024-03-16 13:36:13,161 INFO: Microblog startup [in /Users/gavino/ifa/tutorial/app/__init__.py:31]
2024-03-16 13:36:23,419 INFO: Microblog startup [in /Users/gavino/ifa/tutorial/app/__init__.py:31]
2024-03-16 13:36:49,535 INFO: Microblog startup [in /Users/gavino/ifa/tutorial/app/__init__.py:31]
2024-03-16 13:37:03,510 INFO: Microblog startup [in /Users/gavino/ifa/tutorial/app/__init__.py:31]
2024-03-16 13:38:02,608 INFO: Microblog startup [in /Users/gavino/ifa/tutorial/app/__init__.py:31]
2024-03-16 13:45:41,895 INFO: Microblog startup [in /Users/gavino/ifa/tutorial/app/__init__.py:31]
2024-03-16 13:45:47,253 INFO: Microblog startup [in /Users/gavino/ifa/tutorial/app/__init__.py:31]
2024-03-16 13:48:25,212 INFO: Microblog startup [in /Users/gavino/ifa/tutorial/app/__init__.py:31]
2024-03-16 13:48:30,722 ERROR: Exception on /favorite/5 [POST] [in /Users/gavino/ifa/tutorial/myenv/lib/python3.10/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/Users/gavino/ifa/tutorial/myenv/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/gavino/ifa/tutorial/myenv/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/gavino/ifa/tutorial/myenv/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/gavino/ifa/tutorial/myenv/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/gavino/ifa/tutorial/myenv/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/gavino/ifa/tutorial/app/routes.py", line 99, in favorite
    current_user.favorite(snack)
AttributeError: 'User' object has no attribute 'favorite'
2024-03-16 13:51:23,606 INFO: Microblog startup [in /Users/gavino/ifa/tutorial/app/__init__.py:31]
2024-03-16 13:54:16,122 INFO: Microblog startup [in /Users/gavino/ifa/tutorial/app/__init__.py:31]
2024-03-16 13:54:18,689 ERROR: Exception on /index [GET] [in /Users/gavino/ifa/tutorial/myenv/lib/python3.10/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/Users/gavino/ifa/tutorial/myenv/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/gavino/ifa/tutorial/myenv/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/gavino/ifa/tutorial/myenv/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/gavino/ifa/tutorial/myenv/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/gavino/ifa/tutorial/myenv/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/gavino/ifa/tutorial/app/routes.py", line 19, in index
    return render_template('index.html', title='Home', snacks=snacks.items, next_url=next_url, prev_url=prev_url)
  File "/Users/gavino/ifa/tutorial/myenv/lib/python3.10/site-packages/flask/templating.py", line 151, in render_template
    return _render(app, template, context)
  File "/Users/gavino/ifa/tutorial/myenv/lib/python3.10/site-packages/flask/templating.py", line 132, in _render
    rv = template.render(context)
  File "/Users/gavino/ifa/tutorial/myenv/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/Users/gavino/ifa/tutorial/myenv/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/gavino/ifa/tutorial/app/templates/index.html", line 2, in top-level template code
    {% extends "base.html" %}
  File "/Users/gavino/ifa/tutorial/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/Users/gavino/ifa/tutorial/myenv/lib/python3.10/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Users/gavino/ifa/tutorial/myenv/lib/python3.10/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block 'doc'
    {%- block html %}
  File "/Users/gavino/ifa/tutorial/myenv/lib/python3.10/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block 'html'
    {% block body -%}
  File "/Users/gavino/ifa/tutorial/myenv/lib/python3.10/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block 'body'
    {% block content -%}
  File "/Users/gavino/ifa/tutorial/app/templates/base.html", line 54, in block 'content'
    {% block app_content %}{% endblock %}
  File "/Users/gavino/ifa/tutorial/app/templates/index.html", line 9, in block 'app_content'
    {% for snack in current_user.favorited_snacks.limit(app.config['SNACKS_PER_PAGE']).all() %}
  File "/Users/gavino/ifa/tutorial/myenv/lib/python3.10/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'app' is undefined
2024-03-16 13:54:41,198 INFO: Microblog startup [in /Users/gavino/ifa/tutorial/app/__init__.py:31]
2024-03-16 13:56:21,776 INFO: Microblog startup [in /Users/gavino/ifa/tutorial/app/__init__.py:31]
2024-03-16 14:02:12,439 INFO: Microblog startup [in /Users/gavino/ifa/tutorial/app/__init__.py:31]
